# Generated by Django 2.2.13 on 2020-12-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201206_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Subcategory', verbose_name='категория'),
        ),
    ]
