# Generated by Django 2.2.13 on 2020-12-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201211_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Имя'),
        ),
    ]
