# Generated by Django 2.2.13 on 2020-11-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_name',
            new_name='address',
        ),
    ]
